name:  BuildInfra
on:
  push:
   branches:
     - main
     - release/*

env:
  ENV: "dev"
  TF_STATE_RG: "infrabase" 
  TF_STORAGE_ACCOUNT_PREFIX: "demotf"
  LOCATION: "eastus"
  TF_CONTAINER: "tfstate"

jobs:
  azure-test:
    runs-on: "ubuntu-22.04"
    environment: AZ-DEV
    steps:
      - uses: actions/checkout@v3
      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZ_CREDENTIALS }}'
      - name: prebuild
        run: |
           pwd && echo "workspace is $$GITHUB_WORKSPACE" && \
           ls -al
        
  # pre-build:
  #   runs-on: ubuntu:latest
  #   steps:
  #     - uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: 1.3.7



