name:  BuildInfra
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
   branches:
     - main
     - release/*

env:
  ENV: "dev"
  TF_STATE_RG: "infrabase" 
  TF_STORAGE_ACCOUNT_PREFIX: "demotf"
  LOCATION: "eastus"
  TF_CONTAINER: "tfstate"
  FIRST_RUN: True
jobs:
  azure-test:
    runs-on: "ubuntu-22.04"
    environment: AZ-DEV
    steps:
      - name: Checking source code  
        uses: actions/checkout@v3
      
      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZ_CREDENTIALS }}'

      - name: prebuild
        if: ${{ env.FIRST_RUN == 'True' }}
        run: |
           bash ./pre-build.sh
        env:
          ENV: ${{ env.ENV }}
          TF_STATE_RG: ${{ env.TF_STATE_RG }}
          TF_STORAGE_ACCOUNT_PREFIX: ${{ env.TF_STORAGE_ACCOUNT_PREFIX }}
          LOCATION: ${{ env.LOCATION }}
         # Install the preferred version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.7
      - name: run Terraform
        id: init
        run: terraform init
        working-directory: TF
        
        
                      

        
      
        
  # pre-build:
  #   runs-on: ubuntu:latest
  #   steps:
  #     - uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: 1.3.7



